let cols=8,rows=8,cell=50,board=[],current=1,directions=[[ -1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],gameOver=false,aiMovePending=false
function initBoard(){board=[];for(let y=0;y<rows;y++){let row=[];for(let x=0;x<cols;x++){row.push(0);}board.push(row);}board[3][3]=2;board[3][4]=1;board[4][3]=1;board[4][4]=2}
function inBounds(x,y){return x>=0&&x<cols&&y>=0&&y<rows}
function validFlips(x,y,player){let flips=[];if(!inBounds(x,y)){return flips;}if(board[y][x]!==0){return flips;}let opponent=3-player;for(let d=0;d<directions.length;d++){let dx=directions[d][0];let dy=directions[d][1];let nx=x+dx;let ny=y+dy;let line=[];while(inBounds(nx,ny) && board[ny][nx]===opponent){line.push([nx,ny]);nx+=dx;ny+=dy;}if(inBounds(nx,ny) && board[ny][nx]===player && line.length>0){for(let i=0;i<line.length;i++){flips.push(line[i]);}}}return flips}
function hasLegalMove(player){for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){let f=validFlips(x,y,player);if(f.length>0){return true;}}}return false}
function getAllLegalMoves(player){let moves=[];for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){let f=validFlips(x,y,player);if(f.length>0){moves.push({x:x,y:y,flips:f});}}}return moves}
function applyMove(x,y,player){let f=validFlips(x,y,player);if(f.length===0){return false;}board[y][x]=player;for(let i=0;i<f.length;i++){let px=f[i][0];let py=f[i][1];board[py][px]=player;}return true}
function nextTurn(){current=3-current;aiMovePending=(current===2);if(!hasLegalMove(current)){current=3-current;aiMovePending=(current===2);if(!hasLegalMove(current)){gameOver=true;}}}
function countPieces(){let blacks=0;let whites=0;for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){if(board[y][x]===1){blacks++;}else if(board[y][x]===2){whites++;}}}return {b:blacks,w:whites}}
function setup(){createCanvas(400,400);initBoard();textAlign(LEFT,TOP);noStroke()}
function drawBoard(){background(20,120,20);for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){fill(34,139,34);rect(x*cell,y*cell,cell,cell);stroke(0);strokeWeight(1);line(x*cell,y*cell,(x+1)*cell,y*cell);line(x*cell,(y+1)*cell,(x+1)*cell,(y+1)*cell);noStroke();let v=board[y][x];if(v!==0){if(v===1){fill(0);}else{fill(255);}ellipse(x*cell+cell/2,y*cell+cell/2,cell*0.8,cell*0.8);}}}if(!gameOver && current===1){let moves=getAllLegalMoves(1);for(let i=0;i<moves.length;i++){let mx=moves[i].x;let my=moves[i].y;fill(255,255,0,150);ellipse(mx*cell+cell/2,my*cell+cell/2,cell*0.3,cell*0.3);}}}
function drawHUD(){let scores=countPieces();fill(0,0,0,120);rect(0,rows*cell,400,400-rows*cell);fill(255);textSize(14);text('Black: '+scores.b,10,rows*cell+6);text('White: '+scores.w,120,rows*cell+6);if(gameOver){let msg='Game Over';if(scores.b>scores.w){msg+=' - Black wins';}else if(scores.w>scores.b){msg+=' - White wins';}else{msg+=' - Draw';}text(msg,230,rows*cell+6);}else{let turnMsg=current===1?'Your turn (Black)':'White thinking...';text(turnMsg,230,rows*cell+6);}}
function draw(){drawBoard();drawHUD();if(gameOver){return;}if(current===2 && aiMovePending){let moves=getAllLegalMoves(2);if(moves.length===0){nextTurn();return;}let idx=floor(random(0,moves.length));let mv=moves[idx];applyMove(mv.x,mv.y,2);aiMovePending=false;nextTurn();}}
function mousePressed(){if(gameOver){return;}if(mouseButton!==LEFT){return;}let mx=floor(mouseX/cell);let my=floor(mouseY/cell);if(!inBounds(mx,my)){return;}if(current!==1){return;}let moved=applyMove(mx,my,1);if(!moved){return;}nextTurn()}
